[workspace]
resolver = "3"
members = ["tcp-core", "tcp-tun", "tcp-wasm"]

[profile.release-wasm]
inherits = "release"
lto = true # Compile with Link Time Optimizations
opt-level = "s" # Tell `rustc` to optimize for small code size
